#!/usr/bin/with-contenv bash

if [ -n "${PASSWORD}" ]; then
  AUTH="password"
else
  AUTH="none"
  echo "starting with no password"
fi

if [ -z ${ENABLE_TELEMETRY+x} ]; then
  TELEMETRY_ARG="--disable-telemetry"
else
  TELEMETRY_ARG=""
  echo "telemetry is enabled"
fi

# if [ -z ${LOG_LEVEL+x} ]; then
#   LOG_ARG=""
# else
#   LOG_ARG="--log=${LOG_LEVEL}"
#   echo "log level set to ${LOG_LEVEL}"
# fi

exec \
    s6-setuidgid abc \
		/usr/local/bin/code-server \
			--bind-addr 0.0.0.0:8443 \
			--user-data-dir /config/data \
			--extensions-dir /config/extensions \
			"${TELEMETRY_ARG}" --auth "${AUTH}" \
			/config/workspace
